version: "3.9"

services:
  mongodb:
    env_file:
      - .env
    volumes:
      - data:/mongodb
  api:
    env_file:
      - .env
    volumes:
      - ./api/src:/usr/app
  streamlit:
    env_file:
      - .env
    volumes:
      - ./streamlit:/usr/app

volumes:
  data:
