version: "3.9"

services:
  mongodb:
    build:
      context: ./data
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_DBNAME=${MONGO_DBNAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ADMIN_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ADMIN_PASSWORD}
      - MONGO_API_PASSWORD=${MONGO_API_PASSWORD}
      - MONGO_API_USERNAME=${MONGO_API_USERNAME}
    volumes:
      - data:/mongodb
  api:
    build:
      context: ./api
    restart: always
    ports:
      - 3000:3000
    environment:
      - API_PORT=${API_PORT}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - FLASK_ENV=${FLASK_ENV}
      - MONGO_USERNAME=${MONGO_API_USERNAME}
      - MONGO_PASSWORD=${MONGO_API_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DBNAME=${MONGO_DBNAME}
    links:
      - mongodb
    volumes:
      - ./api/src:/usr/app
  streamlit:
    build:
      context: ./streamlit
    restart: always
    ports:
      - 8501:8501
    environment:
      - API_PORT=${API_PORT}
      - API_HOST=${API_HOST}
    links:
      - api
    volumes:
      - ./streamlit:/usr/app

volumes:
  data:
