version: "3.9"

services:
  mongodb:
    image: teresaromero/palmer-mongodb:latest
    restart: always
    ports:
      - 27017:27017
  api:
    image: teresaromero/palmer-api:latest
    restart: always
    ports:
      - 3000:3000
    links:
      - mongodb
  streamlit:
    image: teresaromero/palmer-streamlit:latest
    restart: always
    ports:
      - 8501:8501
    links:
      - api
