name: Images Build and Push

on:
  push:
    branches: [development]
    paths-ignore:
      - "**/README.md"
      - "**/docs"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
      - name: docker build and push
        env:
          MONGO_DBNAME: ${{ secrets.MONGO_DBNAME }}
          MONGO_ADMIN_USERNAME: ${{ secrets.MONGO_ADMIN_USERNAME }}
          MONGO_ADMIN_PASSWORD: ${{ secrets.MONGO_ADMIN_PASSWORD }}
          MONGO_API_PASSWORD: ${{ secrets.MONGO_API_PASSWORD }}
          MONGO_API_USERNAME: ${{ secrets.MONGO_API_USERNAME }}
          API_PORT: ${{ secrets.API_PORT }}
          FLASK_DEBUG: ${{ secrets.FLASK_DEBUG }}
          FLASK_ENV: ${{ secrets.FLASK_ENV }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          API_URL: ${{ secrets.API_URL }}
        run: |
          docker-compose build
          docker-compose push
