name: Images Build and Push

on:
  push:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
      - name: docker build and push
        env:
          MONGO_DBNAME: ${{ secrets.MONGO_DBNAME }}
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
          MONGO_API_PASSWORD: ${{ secrets.MONGO_API_PASSWORD }}
          MONGO_API_USERNAME: ${{ secrets.MONGO_API_USERNAME }}
          API_PORT: ${{ secrets.API_PORT }}
          FLASK_DEBUG: ${{ secrets.FLASK_DEBUG }}
          FLASK_ENV: ${{ secrets.FLASK_ENV }}
          MONGO_USERNAME: ${{ secrets.MONGO_API_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_API_PASSWORD }}
          MONGO_HOST: ${{ secrets.MONGO_HOST }}
          MONGO_PORT: ${{ secrets.MONGO_PORT }}
          API_HOST: ${{ secrets.API_HOST }}
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.ci.yml push

